---
title: "CO Turtles Exploratory Analyses"
explanation: "Exploratory analysis of spatial-capture-recapture data recorded summer 2018"
author: "Natalie Haydt"
output:
  pdf_document: default
  html_notebook: default
---



```{r, checking working directory}
getwd()
library(lme4)
```

```{r, read in scr data}
scr.data <- read.csv(file = "canalscr_9_1_18.csv")
head(scr.data)
```

```{r, data summary}
summary(scr.data)
```
```{r, histograms}
# need to separate by site?

par(mfrow = c(1,2))
sizes <- hist(scr.data$carapace, main = "Carapace Size Distribution", xlab = "Carapace Size Per Turtle (mm)")
leeches <- hist(scr.data$leeches, main = "Leech Count Distribution", xlab = "Number of Leeches Per Turtle" )

```

```{r, recap rate histogram}

recaps <- read.csv(file = "recaprates_9_1_18.csv")
hist(recaps$prop_recap, breaks = 10, xlab = "Proportion of Recaps", main = "Proportion of Recaptures Across C&O Sites")


```

```{r, subsetting by species}
scr_cpic <- subset(scr.data, species == "CPIC")
scr_sodo <- subset(scr.data, species == "SODO")
scr_cser <- subset(scr.data, species == "CSER")
scr_prub <- subset(scr.data, species == "PRUB")
scr_gins <- subset(scr.data, species == "GINS")
scr_tscr <- subset(scr.data, species == "TSCR")
```

```{r, species summaries}
summary(scr_cpic)
summary(scr_sodo)
summary(scr_cser)
summary(scr_prub)
summary(scr_gins)
## only 1 tscr caught, so did not create summary
```
```{r, histograms per species}
hist(scr_cpic$carapace)
hist(scr_sodo$carapace)
hist(scr_cser$carapace)
hist(scr_prub$carapace)

hist(scr_cpic$leeches)
hist(scr_sodo$leeches)
hist(scr_cser$leeches)
hist(scr_prub$leeches)
```


```{r, size by site per species, ## add in overall}

cpic_size_site <- aov(data = scr_cpic, carapace ~ site)
cpic_size_summary <- summary(cpic_size_site)
cpic_size_summary
cpic_posthoc <- TukeyHSD(cpic_size_site, 'site', conf.level = 0.95)
cpic_posthoc

sodo_size_site <- aov(data = scr_sodo, carapace ~ site)
sodo_size_summary <- summary(sodo_size_site)
sodo_size_summary
sodo_posthoc <- TukeyHSD(sodo_size_site, 'site', conf.level = 0.95)
sodo_posthoc

cser_size_site <- aov(data = scr_cser, carapace ~ site)
cser_size_summary <- summary(cser_size_site)
cser_size_summary
cser_posthoc <- TukeyHSD(cser_size_site, 'site', conf.level = 0.95)
cser_posthoc

prub_size_site <- aov(data = scr_prub, carapace ~ site)
prub_size_summary <- summary(prub_size_site)
prub_size_summary
prub_posthoc <- TukeyHSD(prub_size_site, 'site', conf.level = 0.95)
prub_posthoc

all_size_site <- aov(data = scr.data, carapace ~ site)
all_size_summary <- summary(all_size_site)
all_size_summary
all_size_posthoc <- TukeyHSD(all_size_site, 'site', conf.level = 0.95)
all_size_posthoc

```

```{r, leeches and site; per species and ##overall}

cpic_leeches_site <- aov(data = scr_cpic, leeches ~ site)
cpic_leeches_summary <- summary(cpic_leeches_site)
cpic_leeches_summary
cpic_leeches_posthoc <- TukeyHSD(cpic_leeches_site, 'site', conf.level = 0.95)
cpic_leeches_posthoc

sodo_leeches_site <- aov(data = scr_sodo, leeches ~ site)
sodo_leeches_summary <- summary(sodo_leeches_site)
sodo_leeches_summary
sodo_leeches_posthoc <- TukeyHSD(sodo_leeches_site, 'site', conf.level = 0.95)
sodo_leeches_posthoc

cser_leeches_site <- aov(data = scr_cser, leeches ~ site)
cser_leeches_summary <- summary(cser_leeches_site)
cser_leeches_summary
cser_leeches_posthoc <- TukeyHSD(cser_leeches_site, 'site', conf.level = 0.95)
cser_leeches_posthoc

prub_leeches_site <- aov(data = scr_prub, leeches ~ site)
prub_leeches_summary <- summary(prub_leeches_site)
prub_leeches_summary
prub_leeches_posthoc <- TukeyHSD(prub_leeches_site, 'site', conf.level = 0.95)
prub_leeches_posthoc

all_leeches_site <- aov(data = scr.data, leeches ~ site)
all_leeches_summary <- summary(all_leeches_site)
all_leeches_summary
all_leeches_posthoc <- TukeyHSD(all_leeches_site, 'site', conf.level = 0.95)
all_leeches_posthoc

```

```{r, leeches and species, #add in site as random effect}

leeches_species <- aov(data = scr.data, leeches ~ species)
leeches_species_summary <- summary(leeches_species)
leeches_species_summary
##leeches_species_posthoc <- TukeyHSD(leeches_species, 'leeches', conf.level = 0.95)
##NaNs produced (need to use NA.omit?)
##leeches_species_posthoc

```

```{r, leeches and size - regression, #add in site as random effect}

leeches_size <- aov(data = scr.data, leeches ~ carapace)
leeches_size_summary <- summary(leeches_size)
leeches_size_summary

cpic_leeches_size <- aov(data = scr_cpic, leeches ~ carapace)
cpic_leeches_size_summary <- summary(cpic_leeches_size)
cpic_leeches_size_summary
##cpic_leeches_size_posthoc <- TukeyHSD(cpic_leeches_size, 'carapace', conf.level = 0.95)
##cpic_leeches_size_posthoc

##sodo_leeches_size <- aov(data = scr_sodo, leeches ~ carapace)
##sodo_leeches_size_summary <- summary(sodo_leeches_size)
##sodo_leeches_size_summary
##sodo_leeches_size_posthoc <- TukeyHSD(sodo_leeches_size, 'carapace', conf.level = 0.95)
##sodo_leeches_size_posthoc

##cser_leeches_size <- aov(data = scr_cser, leeches ~ carapace)
##cser_leeches_size_summary <- summary(cser_leeches_size)
##cser_leeches_size_summary
##cser_leeches_size_posthoc <- TukeyHSD(cser_leeches_size, 'carapace', conf.level = 0.95)
##cser_leeches_size_posthoc

##prub_leeches_size <- aov(data = scr_prub, leeches ~ carapace)
##prub_leeches_size_summary <- summary(prub_leeches_size)
##prub_leeches_size_summary
##prub_leeches_size_posthoc <- TukeyHSD(prub_leeches_size, 'carapace', conf.level = 0.95)
##prub_leeches_size_posthoc

```

Based off of Raabe et al. 2014


Based off of Kornilev et al. 2010

